### ISSUE TITLE
Pandoc não encontra o filtro pandoc_abnt

### ISSUE THREAD

**Issue by rscaputo** [limarka/artigo-abntex2-pandoc#2]
Boa noite, @edusantana ,

estou testando este modelo experimental para artigo, mas dá um erro quando executo o comando rake (ver abaixo). Parece que ele não está encontrando o pandoc_abnt, mas a pasta bin do ruby está no PATH do windows. Vc saberia me orientar no que fazer nesse caso? Obrigado.

so: Microsoft Windows [versão 10.0.15063]

erro:
pandoc: Error running filter pandoc_abnt:
Could not find executable 'pandoc_abnt'.
Latexmk: Could not find file [xxx-artigo.tex]
Latexmk: Run number 1 of rule 'pdflatex'
This is pdfTeX, Version 3.14159265-2.6-1.40.18 (MiKTeX 2.9.6350 64-bit)
entering extended mode
Failure to make 'xxx-artigo.pdf'
Collected error summary (may duplicate other messages):
pdflatex: (Pdf)LaTeX failed to generate the expected log file 'xxx-artigo.log'
Latexmk: Did not finish processing file 'xxx-artigo.tex':
(Pdf)LaTeX failed to generate the expected log file 'xxx-artigo.log'

**Comment by edusantana** [comment]
Oi @rscaputo para executar um filtro no windows o pandoc necessita do caminho completo do filtro. A solução que adotei no limarka está descrita no seguite link: ttps://github.com/abntex/limarka/wiki/Instalação-no-Windows#pandoc_abnt_bat

Eu atualizei o arquivo Rakefile para aceitar essa mesma configuração.

1. Certifique-se que configurou a variável de ambiente `PANDOC_ABNT_BAT`
2. Certifique-se que baixou a nova versão do repositório e tente novamente.

Me dá retorno do resultado.

**Comment by rscaputo** [comment]
Funcionou, @edusantana! Muito obrigado pela ajuda...

**Comment by edusantana** [comment]
Ótimo.
